services:
  - type: web
    name: ytube-downloader
    env: node
    buildCommand: ./render-build.sh
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
